@echo off
echo Stopping MongoDB service...
net stop MongoDB

echo Starting MongoDB service...
net start MongoDB

echo Installing dependencies...
call npm install

echo Starting server...
call npm start
